# Generated by Django 3.0.1 on 2022-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220303_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.CharField(default='http://localhost:8000/media/default_profile.jpg', max_length=100),
        ),
    ]
