# Generated by Django 3.0.1 on 2022-03-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220318_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.CharField(default='https://j6s001.p.ssafy.io/media/default_profile.jpg', max_length=100),
        ),
    ]
