# Generated by Django 3.0.1 on 2022-03-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220326_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_backtest',
            field=models.BooleanField(default=False),
        ),
    ]
