# Generated by Django 3.0.1 on 2022-03-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('code_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('market', models.CharField(max_length=10, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('main_product', models.CharField(max_length=100, null=True)),
                ('listing_date', models.CharField(max_length=20)),
                ('settlement_month', models.CharField(max_length=10)),
                ('representative', models.CharField(max_length=50)),
                ('homepage', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('basic_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.BasicInfo')),
                ('face_value', models.FloatField()),
                ('capital_stock', models.FloatField()),
                ('number_of_listings', models.FloatField()),
                ('credit_rate', models.FloatField()),
                ('year_high_price', models.FloatField()),
                ('year_low_price', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('foreigner_percent', models.FloatField()),
                ('substitute_price', models.FloatField()),
                ('per', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('roe', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('ev', models.FloatField(null=True)),
                ('bps', models.FloatField(null=True)),
                ('sales_revenue', models.FloatField(null=True)),
                ('operating_income', models.FloatField(null=True)),
                ('net_income', models.FloatField(null=True)),
                ('shares_outstanding', models.FloatField(null=True)),
                ('shares_outstanding_rate', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['basic_info'],
            },
        ),
        migrations.CreateModel(
            name='DayStock',
            fields=[
                ('stock_seq', models.AutoField(primary_key=True, serialize=False)),
                ('current_price', models.CharField(blank=True, max_length=20, null=True)),
                ('changes', models.CharField(blank=True, max_length=20, null=True)),
                ('chages_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('start_price', models.CharField(blank=True, max_length=20, null=True)),
                ('high_price', models.CharField(blank=True, max_length=20, null=True)),
                ('low_price', models.CharField(blank=True, max_length=20, null=True)),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_price', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('basic_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.BasicInfo')),
            ],
            options={
                'ordering': ['stock_seq'],
            },
        ),
    ]
