# Generated by Django 3.0.1 on 2022-03-08 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoKospi',
            fields=[
                ('code_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('main_product', models.CharField(max_length=100, null=True)),
                ('listing_date', models.CharField(max_length=20)),
                ('settlement_month', models.CharField(max_length=10)),
                ('representative', models.CharField(max_length=50)),
                ('homepage', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['code_number'],
            },
        ),
        migrations.CreateModel(
            name='BoardKospi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info_kospi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.InfoKospi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
