# Generated by Django 3.0.1 on 2022-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infokospi',
            name='homepage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infokospi',
            name='main_product',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
