# Generated by Django 3.0.1 on 2022-03-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystock',
            name='basic_info',
            field=models.ForeignKey(db_column='code_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.BasicInfo'),
        ),
        migrations.AlterModelTable(
            name='daystock',
            table='day_stock',
        ),
    ]
