# Generated by Django 3.0.1 on 2022-03-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_financialkospi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialkospi',
            name='info_kospi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.InfoKospi'),
        ),
    ]
