# Generated by Django 3.0.1 on 2022-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20220307_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infokospi',
            name='sector',
            field=models.CharField(max_length=30),
        ),
    ]
