# Generated by Django 3.0.1 on 2022-03-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20220315_1529'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='daystock',
            table=None,
        ),
    ]
