# Generated by Django 3.0.1 on 2022-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20220308_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialkospi',
            name='bps',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='eps',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='ev',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='net_income',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='operating_income',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='pbr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='per',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='roe',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='sales_revenue',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='shares_outstanding',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialkospi',
            name='shares_outstanding_rate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
