# Generated by Django 3.0.1 on 2022-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20220307_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infokospi',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infokospi',
            name='main_product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infokospi',
            name='sector',
            field=models.CharField(max_length=50),
        ),
    ]
