# Generated by Django 3.0.1 on 2022-03-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220307_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infokospi',
            name='representative',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infokospi',
            name='settlement_month',
            field=models.CharField(max_length=10),
        ),
    ]
