# Generated by Django 3.0.1 on 2022-03-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220310_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoKodaq',
            fields=[
                ('code_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('main_product', models.CharField(max_length=100, null=True)),
                ('listing_date', models.CharField(max_length=20)),
                ('settlement_month', models.CharField(max_length=10)),
                ('representative', models.CharField(max_length=50)),
                ('homepage', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['code_number'],
            },
        ),
        migrations.CreateModel(
            name='FinancialKodaq',
            fields=[
                ('info_kodaq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.InfoKodaq')),
                ('face_value', models.CharField(max_length=20)),
                ('capital_stock', models.CharField(max_length=20)),
                ('number_of_listings', models.CharField(max_length=20)),
                ('credit_rate', models.CharField(max_length=20)),
                ('year_high_price', models.CharField(max_length=20)),
                ('year_low_price', models.CharField(max_length=20)),
                ('market_cap', models.CharField(max_length=20)),
                ('foreigner_percent', models.CharField(max_length=20)),
                ('substitute_price', models.CharField(max_length=20)),
                ('per', models.CharField(max_length=20, null=True)),
                ('eps', models.CharField(max_length=20, null=True)),
                ('roe', models.CharField(max_length=20, null=True)),
                ('pbr', models.CharField(max_length=20, null=True)),
                ('ev', models.CharField(max_length=20, null=True)),
                ('bps', models.CharField(max_length=20, null=True)),
                ('sales_revenue', models.CharField(max_length=20, null=True)),
                ('operating_income', models.CharField(max_length=20, null=True)),
                ('net_income', models.CharField(max_length=20, null=True)),
                ('shares_outstanding', models.CharField(max_length=20, null=True)),
                ('shares_outstanding_rate', models.CharField(max_length=20, null=True)),
            ],
            options={
                'ordering': ['info_kodaq'],
            },
        ),
    ]
