# Generated by Django 3.0.1 on 2022-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20220307_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infokospi',
            name='main_product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
