# Generated by Django 3.0.1 on 2022-03-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_financialkodaq_infokodaq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialKodaq',
            new_name='FinancialKosdaq',
        ),
        migrations.RenameModel(
            old_name='InfoKodaq',
            new_name='InfoKosdaq',
        ),
        migrations.AlterModelOptions(
            name='financialkosdaq',
            options={'ordering': ['info_kosdaq']},
        ),
        migrations.RenameField(
            model_name='financialkosdaq',
            old_name='info_kodaq',
            new_name='info_kosdaq',
        ),
    ]
