# Generated by Django 3.0.1 on 2022-03-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20220307_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.InfoKospi')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
