# Generated by Django 3.0.1 on 2022-03-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_boardkonex_boardkosdaq_commentkonex_commentkosdaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardkosdaq',
            name='info_kosdaq',
        ),
        migrations.RemoveField(
            model_name='boardkosdaq',
            name='user',
        ),
        migrations.RemoveField(
            model_name='boardkospi',
            name='info_kospi',
        ),
        migrations.RemoveField(
            model_name='boardkospi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentkonex',
            name='board_konex',
        ),
        migrations.RemoveField(
            model_name='commentkonex',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentkosdaq',
            name='board_kosdaq',
        ),
        migrations.RemoveField(
            model_name='commentkosdaq',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentkospi',
            name='board_kospi',
        ),
        migrations.RemoveField(
            model_name='commentkospi',
            name='user',
        ),
        migrations.DeleteModel(
            name='BoardKonex',
        ),
        migrations.DeleteModel(
            name='BoardKosdaq',
        ),
        migrations.DeleteModel(
            name='BoardKospi',
        ),
        migrations.DeleteModel(
            name='CommentKonex',
        ),
        migrations.DeleteModel(
            name='CommentKosdaq',
        ),
        migrations.DeleteModel(
            name='CommentKospi',
        ),
    ]
