# Generated by Django 3.0.1 on 2022-03-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20220315_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayStock',
            new_name='DayStockInfo',
        ),
    ]
