# Generated by Django 3.0.1 on 2022-03-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20220328_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('result_close', models.FloatField()),
                ('financial_info', models.ForeignKey(db_column='code_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.FinancialInfo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
