# Generated by Django 3.0.1 on 2022-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='final_profit_loss',
        ),
        migrations.AddField(
            model_name='result',
            name='final_earn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
