# Generated by Django 3.0.1 on 2022-04-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='dayhistory',
            name='day_earn',
            field=models.BigIntegerField(),
        ),
    ]
