# Generated by Django 3.0.1 on 2022-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_auto_20220404_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='final_earn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
